"""add market dashboard tables

Revision ID: 1403f6cdbc3a
Revises: daf8faa7a116
Create Date: 2026-08-20 19:36:02.193837
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1403f6cdbc3a'
down_revision: Union[str, None] = 'daf8faa7a116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amc_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.String(length=150), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('listed_count', sa.Integer(), nullable=False),
    sa.Column('market_share', sa.Float(), nullable=False),
    sa.Column('trend', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auction_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('on_auction', sa.Integer(), nullable=False),
    sa.Column('sold', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_kpis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('trend', sa.String(length=50), nullable=False),
    sa.Column('trend_up', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_kpis')
    op.drop_table('auction_stats')
    op.drop_table('amc_stats')
    # ### end Alembic commands ###
